###############################################################################
# phase3/codebuild/codebuild.tf
#
# CodeBuild GitHub Actions self-hosted runner using PAT authentication.
#
# The GitHub App (CodeStar Connections) approach was abandoned because:
#   - aws_codestarconnections_resource_policy does not exist in the provider
#   - CodeBuild webhook creation with WORKFLOW_JOB_QUEUED requires the
#     connection resource policy which cannot be set via Terraform
#
# PAT-based auth works cleanly with WORKFLOW_JOB_QUEUED webhook filter
# which is what registers this as a GitHub Actions runner project.
###############################################################################

# ---------------------------------------------------------------------------
# GitHub PAT source credential
# One credential per server_type per region. Terraform updates in place
# if one already exists - safe to re-run.
# ---------------------------------------------------------------------------
resource "aws_codebuild_source_credential" "github" {
  auth_type   = "PERSONAL_ACCESS_TOKEN"
  server_type = "GITHUB"
  token       = var.github_token
}

# ---------------------------------------------------------------------------
# CodeBuild project
# ---------------------------------------------------------------------------
resource "aws_codebuild_project" "runner" {
  name          = "${local.name_prefix}-runner"
  description   = local.project_description
  service_role  = aws_iam_role.codebuild.arn
  build_timeout = var.build_timeout

  artifacts {
    type = "NO_ARTIFACTS"
  }

  environment {
    compute_type                = var.compute_type
    image                       = "aws/codebuild/standard:7.0"
    type                        = "LINUX_CONTAINER"
    privileged_mode             = true
    image_pull_credentials_type = "CODEBUILD"

    environment_variable {
      name  = "AWS_DEFAULT_REGION"
      value = var.aws_region
    }
    environment_variable {
      name  = "AWS_ACCOUNT_ID"
      value = var.aws_account_id
    }
    environment_variable {
      name  = "EKS_CLUSTER_NAME"
      value = var.cluster_name
    }
    environment_variable {
      name  = "ECR_REGISTRY"
      value = local.ecr_registry
    }
    environment_variable {
      name  = "ENVIRONMENT"
      value = var.environment
    }
    environment_variable {
      name  = "GITHUB_ORGANIZATION"
      value = var.github_organization
    }
    # Only meaningful in single-repo (REPOSITORY) mode. In org-wide mode the
    # actual repo varies per job, so this is left blank rather than pinned.
    environment_variable {
      name  = "GITHUB_REPOSITORY"
      value = local.is_org_scope ? "" : var.github_repository
    }
  }

  vpc_config {
    vpc_id             = var.vpc_id
    subnets            = var.private_subnet_ids
    security_group_ids = [aws_security_group.codebuild.id]
  }

  source {
    type     = "GITHUB"
    location = local.source_location

    # git_clone_depth / report_build_status are only meaningful (and only
    # accepted by the CodeBuild API) when location is a real, clonable repo
    # URL. The CODEBUILD_DEFAULT_WEBHOOK_SOURCE_LOCATION placeholder used for
    # org-wide runners rejects CreateProject with "source location must be a
    # valid git location" if these are present, so they're omitted (null) in
    # that mode.
    git_clone_depth     = local.is_org_scope ? null : 1
    report_build_status = local.is_org_scope ? null : false
  }

  # A pinned branch only makes sense when this project targets one specific
  # repo. In org-wide mode, each job's own workflow determines the ref.
  source_version = local.is_org_scope ? null : var.github_branch

  logs_config {
    cloudwatch_logs {
      group_name  = aws_cloudwatch_log_group.codebuild.name
      stream_name = "runner"
      status      = "ENABLED"
    }
  }

  depends_on = [aws_codebuild_source_credential.github]

  tags = var.tags
}

# ---------------------------------------------------------------------------
# Webhook with WORKFLOW_JOB_QUEUED filter.
# This is what registers the project as a GitHub Actions runner in AWS Console.
# GitHub dispatches jobs to this runner when workflow uses:
#   runs-on: codebuild-<project-name>-${{ github.run_id }}-${{ github.run_attempt }}
#
# webhook_scope = "GITHUB_ORGANIZATION" registers this at the org level
# instead of on a single repo, so every repo in github_organization can
# dispatch WORKFLOW_JOB_QUEUED jobs to this one project. This requires the
# PAT (var.github_token) to be a classic token with the admin:org_hook scope,
# generated by an account with owner access on the organization - a repo-only
# admin:repo_hook token is not sufficient and will fail with an
# OAuthProviderException/permission error.
# ---------------------------------------------------------------------------
resource "aws_codebuild_webhook" "runner" {
  project_name = aws_codebuild_project.runner.name
  build_type   = "BUILD"

  filter_group {
    filter {
      type    = "EVENT"
      pattern = "WORKFLOW_JOB_QUEUED"
    }
  }

  dynamic "scope_configuration" {
    for_each = local.is_org_scope ? [1] : []
    content {
      name  = var.github_organization
      scope = "GITHUB_ORGANIZATION"
    }
  }
}
